apiVersion: v2
name: edgehog
description: A Helm chart Edgehog, the Open Device Manager Platform.

# dependencies:
#   - name: cert-manager
#     version: 1.17.1
#     repository: https://charts.jetstack.io
#   - name: ingress-nginx
#     version: 4.11.0
#     repository: https://kubernetes.github.io/ingress-nginx
#   - name: astarte-operator
#     version: 24.5.1
#     repository: https://helm.astarte-platform.org


# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application (Edgehog) being deployed.
appVersion: "0.9.2"
